baseURL = "https://jellybird.ca"
theme = "blowfish"
defaultContentLanguage = "en"

enableRobotsTXT = true
summaryLength = 30

[pagination]
  pagerSize = 10

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"

[outputs]
  home = ["HTML", "RSS", "JSON"]
