baseURL = "https://jellybird.ca"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Jellybird"
theme = "blowfish"

[pagination]
pagerSize = 10

enableRobotsTXT = true
summaryLength = 30

[params]
  description = "Homepage for Jellybird Art"
  
  [params.author]
    name = "Sara Wong"

  [params.fonts]
    title = "Hubballi"
    body = "Barlow Semi Condensed"

[taxonomies]
  tag = "art"
  category = "art"
  author = "Sara Wong"

[outputs]
  home = ["HTML", "RSS", "JSON"]
