languageCode = "en-us"
languageName = "English"
weight = 1

title = "jellybird"

[params]
description = "Homepage for Jellybird Art"

[params.author]
name = "jellybird"
image = "img/author.jpg"
headline = "i do be printing"
bio = "I'm a little tea pot"
# links = [{ twitter = "https://twitter.com/username" }]
