# Blowfish theme parameters
# See https://blowfish.page/docs/configuration/#theme-parameters

colorScheme = "blowfish"
defaultAppearance = "dark"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

[header]
  layout = "fixed"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "custom"
  showRecent = false

[article]
  showDate = true
  showAuthor = true
  showHero = true
  showBreadcrumbs = true
  showTableOfContents = true
  showRelatedContent = true
  showReadingTime = true

[list]
  showHero = true
  showBreadcrumbs = false
  showCards = true
