baseURL = "https://cmcconomy.github.io/jellybird-site/"
languageCode = "en-us"
title = "Jellybird"
theme = "blowfish"
paginate = 10

[params]
  description = "Homepage for Jellybird Art"
  
  [params.author]
    name = "Sara Wong"
